# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlphaAcademy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlphaAcademy
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'WechatKit'



  target 'AlphaAcademyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlphaAcademyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
